import DockLayoutCore
import Foundation

let usage = """
docklayout \(DockLayoutVersion.current)

Usage:
  docklayout                 Pick a layout and switch to it
  docklayout save <name>     Snapshot the current Dock
  docklayout load <name>     Switch to a saved layout
  docklayout list            List saved layouts
  docklayout active          Print the layout that matches the Dock right now
  docklayout show [name]     Print a layout, or the live Dock
  docklayout delete <name>   Delete a saved layout
  docklayout undo            Restore the Dock from before the last switch
  docklayout restart-dock    Start the Dock again if it isn't showing

Layouts are stored in ~/.config/docklayout/layouts.

"""

struct Failure: Error {
    let message: String
}

func printError(_ message: String) {
    FileHandle.standardError.write(Data((message + "\n").utf8))
}

func label(for item: Any) -> String {
    guard let item = item as? [String: Any] else { return "[item]" }
    let tile = item["tile-data"] as? [String: Any] ?? [:]
    for key in ["file-label", "label"] {
        if let text = tile[key] as? String, !text.trimmingCharacters(in: .whitespaces).isEmpty {
            return text
        }
    }
    guard let kind = item["tile-type"] as? String else { return "[item]" }
    switch kind {
    case "spacer-tile": return "— spacer —"
    case "small-spacer-tile": return "— small spacer —"
    case "flex-spacer-tile": return "— flexible spacer —"
    default: return "[\(kind)]"
    }
}

func format(_ layout: Layout, heading: String) -> String {
    var lines = [heading]
    for (key, title) in [("persistent-apps", "Apps"), ("persistent-others", "Folders and stacks")] {
        let items = layout[key] as? [Any] ?? []
        lines.append("\(title) (\(items.count))")
        if items.isEmpty {
            lines.append("  (empty)")
        }
        for (index, item) in items.enumerated() {
            let number = String(index + 1)
            lines.append("  \(String(repeating: " ", count: max(0, 2 - number.count)))\(number). \(label(for: item))")
        }
    }
    return lines.joined(separator: "\n")
}

func load(_ name: String, with layouts: DockLayouts) throws {
    do {
        try layouts.load(name)
    } catch DockLayoutError.notFound {
        throw Failure(message: "No saved layout \"\(name)\". Arrange the Dock, then run: docklayout save \(name)")
    }
    print("Loaded Dock layout: \(name)")
}

func interactive(_ layouts: DockLayouts) throws {
    let names = layouts.names()
    guard !names.isEmpty else {
        throw Failure(message: "No Dock layouts saved. Arrange the Dock, then run: docklayout save Work")
    }
    print("Dock layouts")
    for (index, name) in names.enumerated() {
        print("  \(index + 1). \(name)")
    }
    print("Load (number or name, q to quit): ", terminator: "")
    guard let line = readLine() else {
        print()
        return
    }
    let choice = line.trimmingCharacters(in: .whitespaces)
    if ["", "q", "quit"].contains(choice.lowercased()) {
        return
    }
    if let number = Int(choice), choice.allSatisfy(\.isNumber) {
        guard names.indices.contains(number - 1) else { throw Failure(message: "No layout numbered \(choice).") }
        try load(names[number - 1], with: layouts)
        return
    }
    guard let match = names.first(where: { $0.lowercased() == choice.lowercased() }) else {
        throw Failure(message: "No saved layout \"\(choice)\".")
    }
    try load(match, with: layouts)
}

// MARK: Raycast

let generatedMark = "@generated by docklayout"

func raycastDirectory() -> URL {
    if let override = ProcessInfo.processInfo.environment["DOCKLAYOUT_RAYCAST_DIR"], !override.isEmpty {
        return URL(fileURLWithPath: (override as NSString).expandingTildeInPath, isDirectory: true)
    }
    return FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent("raycast-scripts", isDirectory: true)
}

/// Single-quotes for zsh, like Python's shlex.quote.
func shellQuote(_ text: String) -> String {
    let safe = CharacterSet(charactersIn: "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@%+=:,./-_")
    if !text.isEmpty, text.unicodeScalars.allSatisfy(safe.contains) {
        return text
    }
    return "'" + text.replacingOccurrences(of: "'", with: "'\"'\"'") + "'"
}

/// The path this command was run as. Keeps a symlink unresolved so the
/// scripts follow the app (or a Homebrew upgrade) instead of a fixed copy.
func cliPath() -> String {
    let raw = CommandLine.arguments[0]
    if raw.hasPrefix("/") {
        return raw
    }
    if raw.contains("/") {
        return URL(fileURLWithPath: raw).standardizedFileURL.path
    }
    for directory in (ProcessInfo.processInfo.environment["PATH"] ?? "").split(separator: ":") {
        let candidate = "\(directory)/\(raw)"
        if FileManager.default.isExecutableFile(atPath: candidate) {
            return candidate
        }
    }
    return raw
}

func raycastScript(title: String, mode: String, description: String, extra: String = "", body: String) -> String {
    """
    #!/bin/zsh
    # Required parameters:
    # @raycast.schemaVersion 1
    # @raycast.title \(title)
    # @raycast.mode \(mode)

    # Optional parameters:
    # @raycast.icon 🖥️
    # @raycast.packageName Dock Layouts
    # @raycast.description \(description)
    \(extra)
    # \(generatedMark)
    \(body)

    """
}

func refreshRaycast(_ names: [String]) throws -> URL {
    let directory = raycastDirectory()
    let manager = FileManager.default
    try manager.createDirectory(at: directory, withIntermediateDirectories: true)
    let cli = shellQuote(cliPath())
    var expected: Set<String> = ["set-dock-layout.sh"]

    func write(_ name: String, _ content: String) throws {
        let url = directory.appendingPathComponent(name)
        try content.write(to: url, atomically: true, encoding: .utf8)
        try manager.setAttributes([.posixPermissions: 0o755], ofItemAtPath: url.path)
    }

    if names.isEmpty {
        try write("set-dock-layout.sh", raycastScript(
            title: "Set Dock Layout", mode: "compact",
            description: "Save a Dock layout, then run this again",
            body: "echo \"No Dock layouts yet. Arrange the Dock, then run: docklayout save Work\"\nexit 1"
        ))
    } else {
        let options = names.map { ["title": $0, "value": $0] }
        let argument: [String: Any] = ["type": "dropdown", "placeholder": "Layout", "data": options]
        let json = String(decoding: try JSONSerialization.data(withJSONObject: argument, options: [.sortedKeys]), as: UTF8.self)
        try write("set-dock-layout.sh", raycastScript(
            title: "Set Dock Layout", mode: "compact",
            description: "Switch between saved macOS Dock layouts",
            extra: "# @raycast.argument1 \(json)\n",
            body: "exec \(cli) load \"$1\""
        ))
        for name in names {
            let file = "dock-\(name.lowercased()).sh"
            expected.insert(file)
            try write(file, raycastScript(
                title: "Dock: \(name)", mode: "silent",
                description: "Switch the Dock to the \(name) layout",
                body: "exec \(cli) load \(shellQuote(name))"
            ))
        }
    }

    // Remove scripts we generated for layouts that no longer exist.
    for url in (try? manager.contentsOfDirectory(at: directory, includingPropertiesForKeys: nil)) ?? []
    where url.pathExtension == "sh" && !expected.contains(url.lastPathComponent) {
        if let text = try? String(contentsOf: url, encoding: .utf8), text.contains(generatedMark) {
            try? manager.removeItem(at: url)
        }
    }
    return directory
}

func run(_ args: [String]) throws -> Int32 {
    let layouts = DockLayouts.system()

    if args.first == "--version" || args.first == "-V" {
        print(DockLayoutVersion.current)
        return 0
    }
    if args.isEmpty, isatty(STDIN_FILENO) != 0, isatty(STDOUT_FILENO) != 0 {
        try interactive(layouts)
        return 0
    }
    if args.isEmpty {
        printError(usage)
        return 1
    }
    if ["help", "-h", "--help"].contains(args[0]) {
        print(usage, terminator: "")
        return 0
    }

    switch (args[0], args.count) {
    case ("save", 2):
        try layouts.save(args[1])
        print("Saved Dock layout: \(args[1])")
    case ("load", 2):
        try load(args[1], with: layouts)
    case ("list", 1):
        let names = layouts.names()
        print(names.isEmpty ? "No Dock layouts saved." : names.joined(separator: "\n"))
    case ("active", 1):
        if let name = layouts.activeName() {
            print(name)
        }
    case ("show", 1), ("current", 1):
        print(format(try layouts.liveLayout(), heading: "Live Dock"))
    case ("show", 2):
        print(format(try layouts.store.read(args[1]), heading: args[1]))
    case ("delete", 2):
        try layouts.delete(args[1])
        print("Deleted Dock layout: \(args[1])")
    case ("undo", 1):
        let restored = try layouts.undo()
        print("Restored Dock from \(restored)")
    case ("restart-dock", 1):
        try SystemDock.restart()
        print("The Dock is running.")
    case ("raycast", 1):
        print(try refreshRaycast(layouts.names()).path)
    default:
        printError(usage)
        return 1
    }
    return 0
}

do {
    exit(try run(Array(CommandLine.arguments.dropFirst())))
} catch let failure as Failure {
    printError(failure.message)
    exit(1)
} catch {
    printError(error.localizedDescription)
    exit(1)
}
